# Python

- Introducción (tipado, estructras de datos base, funciones nativas)
- Estructuras de datos (indexación, filtrado)
- Estructuras de control de flujo (condiciales [if, else, elif], blucles for, bucles while)
- Definición de funciones (reusabilidad y modularidad; funciones lambda, funciones de orden superior: map, filter, resume)
- Librerias

## Librerías de python

Paquete de información que convencionalmente contiene: datos, funciones, métodos, tipos de objetos, etc. permite extender la funcionalidad base de Python

In [2]:
# Numpy
'''
from numpy import * 
from sklearn import linear_model
'''

import numpy as np # Array: escalar (dim = 0), vector (dim = 1), matriz (dim = 2), tensor (dim > 2)

In [7]:
vector = list(range(1,11))
print(vector)
print(type(vector))
print(len(vector))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>
10


In [8]:
matriz = [list(range(6)),list(range(5,11)),list(range(10,16)),list(range(15,21)),list(range(20,26))]
print(matriz)
print(type(matriz))
print(len(matriz))

[[0, 1, 2, 3, 4, 5], [5, 6, 7, 8, 9, 10], [10, 11, 12, 13, 14, 15], [15, 16, 17, 18, 19, 20], [20, 21, 22, 23, 24, 25]]
<class 'list'>
5


In [9]:
vector = np.array(vector)
matriz = np.array(matriz)

In [10]:
print(vector)
print(type(vector))
print(len(vector))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
10


In [11]:
print(matriz)
print(type(matriz))
print(len(matriz))

[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]
 [20 21 22 23 24 25]]
<class 'numpy.ndarray'>
5


In [24]:
# Indexing and slicing

vector[5] 
vector[2:4]
vector[2:8:2] # start, stop, step
vector[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [30]:
matriz[1:4]
matriz[1,0] #Indexación a través de un sistema de referenciación de coordenadas bidimensionales (fila,columna)
matriz[1:5,1:3]

array([[ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]])

In [32]:
# Métodos utiles en np para creación de vectors

vector1 = np.random.randint(300,1000,20)
vector1

# Cambio de tipado: casting (cambio deliberado del objeto) coerción (automatico)


array([584, 888, 634, 501, 627, 303, 539, 502, 526, 459, 596, 937, 407,
       561, 538, 461, 455, 629, 861, 492])

In [61]:
def randint_mia(low,high,size=1):
    import random
    import numpy as np
    vector = []
    for i in range(size):
        vector.append(random.randint(300,1000))
    return np.array(vector)

In [62]:
randint_mia(300,1000,20)

array([609, 628, 687, 696, 500, 901, 331, 669, 363, 994, 532, 389, 724,
       384, 817, 856, 589, 575, 575, 773])

In [67]:
vector1.astype(np.str_)

array(['584', '888', '634', '501', '627', '303', '539', '502', '526',
       '459', '596', '937', '407', '561', '538', '461', '455', '629',
       '861', '492'], dtype='<U11')

In [68]:
matriz.ndim

2